apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    App: Web
    Type: Prod
  name: nginx-server
spec:
  selector:
    App: Web
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
