apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: WebServer
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      App: Web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        App: Web
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
